name: CI
on:
  push:
  pull_request:
  schedule:
    # Run every Mondays at 8.30 am
    - cron: '30 8 * * 1'

jobs:
  build:
    name: ROS noetic on focal
    runs-on: ubuntu-latest
    #container:
    #  image: rostooling/setup-ros-docker:ubuntu-focal-ros-noetic-ros-base-latest
    steps:
      - uses: actions/checkout@v4
      - uses: https://github.com/ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: noetic
      - uses: https://github.com/romainreignier/action-ros-ci@feature/ssh_port
        with:
          package-name: p_rosbridge_server_cpp
          target-ros1-distro: noetic
          vcs-repo-file-url: "${{ github.workspace }}/.github/workflows/deps.repos"
